# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/discord',
                'doc_host': 'https://Dmaturana81.github.io',
                'git_url': 'https://github.com/Dmaturana81/discord',
                'lib_path': 'discord'},
  'syms': {'discord.core': {'discord.core.foo': ('core.html#foo', 'discord/core.py')}}}
